### ISSUE TITLE
Contoh

### ISSUE THREAD

**Issue by mf4dl1** [geoenvo/mhews#1]
# Background

1. Tampilan Multi Hazard Early Warning System (MHEWS) saat ini belum user friendly. Untuk itu perlu perubahan pada tampilan MHEWS agar lebih memudahkan user menggunakan fiture yang ada
2. Tampilan login awal MHEWS masih perlu untuk didesign kembali dan ditambahkan layer status user-nya pada saat login
3. Tampilan awal MHEWS setelah user login berupa Maps, masih perlu untuk didesign kembali (belum user friendly). Untuk font nya perlu diperbesar untuk mempermudah user yang melakukan pemantauan melihat langsung di layar besar ruang Pastigana (seperti tampilan awal SmartClim)

# User Interface
![image](https://cloud.githubusercontent.com/assets/4919662/22723399/8edcee34-edf0-11e6-93f2-0e5451515b16.png)

## Status Waspada
Status | Keterangan
---|---
Waspada | Level 1, BPBD menyebarkan informasi kepada penduduk.
Awas | Level 1, BPBD menyebarkan informasi kepada penduduk.

Mas @senoadiw  tolong dibantu halaman webnya ya..

**Comment by mf4dl1** [comment]
Hi @MilaGEO , sebaiknya untuk setiap desain saya review dl ya sebelum masuk ke tim developer (seno dkk.) setelah itu baru minta masukan ke mas @senoadiw  dkk.

Komentar saya untuk Issue ini:
1. UI di atas masih belum jelas, hanya berupa peta saja? tombol2 nya ada di mana? header? legenda?
2. Setelah dibuat lengkap, masukan "Deskripsi" yang menjelaskan jika diklik tombol ini, apa actionnya, dll.

**Comment by senoadiw** [comment]
This issue was moved to pastigana/mhews#1
